apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  selector:
    matchLabels:
      app: haproxy
  endpoints:
  - port: metrics