resources:
- ../base
namePrefix: external-
patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: READSB_NET_CONNECTOR
        value: "cnvr.io,30005,beast_out;feed.adsb.one,60004,beast_out"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
       name: READSB_EXTRA_ARGS
       value: "--debug=nS --net-beast-reduce-interval=10"
