resources:
- ../base
namePrefix: hub-

images:
- name: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
  newName: ghcr.io/katlol/readsb
  newTag: 6f28ce612cdf284eda7a3c316d17f6439d5afd39
patches:
- target:
    kind: Deployment
  # Change command completely
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command
      value:
        - /usr/local/bin/readsb
        - --net
        - --quiet
        - --write-json=/run/readsb
        - --json-reliable=2
        - --net-ri-port=30001
        - --net-ro-port=30002
        - --net-sbs-port=30003
        - --net-bi-port=30004,30104
        - --net-bo-port=30005
        - --net-beast-reduce-out-port=30006
        - --net-json-port=30047
        - --net-api-port=30152
        - --net-sbs-in-port=32006
        - --max-range=99999
        - --net-connector=planes-readsb,30004,beast_out
        - --net-connector=planes-readsb-test,30004,beast_out
        - --net-sbs-in-port=32006
        - --debug=nS
        - --net-receiver-id
        - --write-prom=/run/readsb/metrics
        - --forward-mlat
        - --net-garbage=30419
