# create GitRepository
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: infra
  namespace: adsblol
spec:
  interval: 1m
  ref:
    branch: main
  url: ssh://git@github.com/adsblol/infra.git
  secretRef:
    name: infra
---
# create Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: adsblol
spec:
  interval: 1m
  path: ./manifests/default
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
  validation: client
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infra
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
  - remoteRef:
      key: adsblol/infra
      property: identity
    secretKey: identity
  - remoteRef:
      key: adsblol/infra
      property: known_hosts
    secretKey: known_hosts
  refreshInterval: 1m
