# create GitRepository
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: infra
  namespace: adsblol
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/adsblol/infra.git
---
# create Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: adsblol
spec:
  interval: 1m
  path: ./manifests/default
  prune: false
  sourceRef:
    kind: GitRepository
    name: infra
  validation: client
