# StatefulSet for ghcr.io/sdr-enthusiasts/docker-tar1090
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: readsb
spec:
  serviceName: readsb
  template:
    spec:
      volumes: []
      containers:
        - name: readsb
          volumeMounts: []
          image: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          startupProbe:
            tcpSocket:
              port: 30004
            initialDelaySeconds: 15
          livenessProbe:
            tcpSocket:
              port: 30004
            initialDelaySeconds: 15
          readinessProbe:
            tcpSocket:
              port: 30004
            initialDelaySeconds: 15
          ports:
            - containerPort: 80
              name: http
            - containerPort: 30004
              name: adsb-in
            - containerPort: 30005
              name: adsb-out
            - containerPort: 30006
              name: adsb-out-r
            - containerPort: 32006
              name: sbs-in
            - containerPort: 32007
              name: sbs-out
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: LAT
              value: "52.38"
            - name: LONG
              value: "4.897"
            - name: MLATPORT
              value: "30105"
            - name: READSB_MAX_RANGE
              value: "99999"
            - name: "TAR1090_SITESHOW"
              value: "false"
            - name: TAR1090_RANGE_OUTLINE_WIDTH
              value: "0.0"
            - name: TAR1090_ACTUAL_RANGE_OUTLINE_WIDTH
              value: "0.0"
            - name: READSB_RANGE_OUTLINE_HOURS
              value: "0.0"
            - name: TAR1090_RANGE_OUTLINE_DASH
              value: "[0,0]"
            - name: TAR1090_DEFAULTZOOMLVL
              value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: readsb
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: adsb-in
      port: 30004
      targetPort: adsb-in
    - name: adsb-out
      port: 30005
      targetPort: adsb-out
    - name: adsb-out-r
      port: 30006
      targetPort: adsb-out-r
