resources:
  - ../base
namePrefix: to-adsb-fi-
patches:
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: READSB_NET_CONNECTOR
          value: "feed.adsb.fi,30004,beast_reduce_out"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
         name: READSB_EXTRA_ARGS
         value: "--debug=nS"
