resources:
- ../base
namePrefix: ingest-
commonLabels:
  service: public
# Patch:
# add ENV
images:
- name: ghcr.io/sdr-enthusiasts/docker-tar1090:latest
  newName: ghcr.io/katlol/readsb
patches:
- target:
    kind: Deployment
  # Change command completely
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command
      value:
      - /usr/local/bin/readsb-uuid
      - --net
      - --quiet
      - --write-json=/run/readsb
      - --json-reliable=2
      - --net-ri-port=30001
      - --net-ro-port=30002
      - --net-sbs-port=30003
      - --net-bi-port=30004,30104
      - --net-bo-port=30005
      - --net-beast-reduce-out-port=30006
      - --net-json-port=30047
      - --net-api-port=30152
      - --net-sbs-in-port=32006
      - --net-connector=external-readsb,30004,beast_reduce_out
      - --debug=nS
      - --net-ingest
      - --net-receiver-id
      - --write-prom=/run/readsb/metrics
      - --write-receiver-id-json
      - --net-beast-reduce-interval=0.25
