resources:
- ../base
namePrefix: ingest-
commonLabels:
  service: public
# Patch:
# add ENV
patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: READSB_NET_CONNECTOR
        value: "external-readsb,30004,beast_reduce_out"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
       name: READSB_EXTRA_ARGS
       value: "--debug=nS --net-ingest --net-receiver-id --write-prom=/run/readsb/metrics --write-receiver-id-json --net-beast-reduce-interval=0.5"
