apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
      - name: redis
        image: redis:alpine
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          requests:
            cpu: 1m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 3
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 3
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
