resources:
  - ../base
  - resources.yaml
namePrefix: planes-
patches:
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: READSB_EXTRA_ARGS
          value: "--debug=nS"
    # TODO fix me!
  # Add a 2nd rclone container
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/template/spec/containers/1
        value:
          name: rclone
          image: "rclone/rclone"
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          args:
            - -v
            - mount
            - "adsblol:adsblol"
            - /adsblol/adsblol
            - --config=/etc/rclone/rclone.conf
            - --allow-non-empty
            - --allow-other
            - --poll-interval=9s
            - --dir-cache-time=9999h
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "fusermount -uz /adsblol"]
          resources:
            requests:
              cpu: 250m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 2048Mi
          volumeMounts:
            - name: config-data
              mountPath: /etc/rclone
            - name: adsblol
              mountPath: /adsblol
              mountPropagation: Bidirectional
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: adsblol
          emptyDir: {}
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: state
          persistentVolumeClaim:
            claimName: planes-state
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: config-data
          secret:
            secretName: adsblol-rclone
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: adsblol
          mountPath: /var/globe_history/2023
          subPath: adsblol
          mountPropagation: HostToContainer
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: state
          mountPath: /var/globe_history/internal_state
